# Generated by Django 3.1.4 on 2021-05-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
