# Generated by Django 3.1.4 on 2021-05-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrate_units',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='energy',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_units',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_units',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
