# Generated by Django 3.1.4 on 2021-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
